{% set version = "4.4.0" %}

package:
  name: apptools
  version: {{ version }}

source:
  git_url: https://github.com/enthought/apptools
  git_tag: {{ version }}

build:
  number: 0

requirements:
  run:
    - python
    - traitsui
    - pyface
    - configobj
  build:
    - python
    - traitsui
    - pyface
    - configobj

test:
  imports:
    - apptools
  commands:
    - python -c "import apptools;"

about:
  home: http://docs.enthought.com/apptools/
  license: BSD
  summary: TraitsUI - Traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
