{% set version = "4.6.1" %}
# TODO: fix version string

package:
  name: enable
  version: {{ version }}

source:
  fn: enable-{{ version }}.tar.gz
  url: https://github.com/enthought/enable/archive/{{ version }}.tar.gz
  sha256: be732ef383acd9344bff5f30948ba68a6be42f945ebe561ef566bf1549d1f858

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - numpy
    - swig
    - cython  # [osx]
    - xorg-libx11 1.6.*  # [linux]

  run:
    - python
    - numpy
    - pillow
    - traits
    - pyface
    - traitsui
    - six
    - apptools  # optional
    - xorg-libx11 1.6.*  # [linux]
#    - kiwi  # or kiwisolver?  (optional)
#  various other optional backends

test:
  imports:
    - enable

about:
  home: http://docs.enthought.com/enable
  license: BSD 3-clause
  summary: low-level drawing and interaction

extra:
  recipe-maintainers:
    - grlee77
