{% set version = "2.05.1" %}

package:
  name: astyle
  version: {{ version }}

source:
  fn: astyle_{{ version }}_macosx.tar.gz # [osx]
  url: http://downloads.sourceforge.net/project/astyle/astyle/astyle%20{{ version }}/astyle_{{ version }}_macosx.tar.gz # [osx]
  md5: cb7cdfa645c155bb3ad20bc7d726f023 # [osx]
  fn: astyle_{{ version }}_linux.tar.gz # [linux]
  url: http://downloads.sourceforge.net/project/astyle/astyle/astyle%20{{ version }}/astyle_{{ version }}_linux.tar.gz # [linux]
  md5: 4142d178047d7040da3e0e2f1b030a1a # [linux]
#   fn: AStyle_{{ version }}_windows.zip # [win]
#   url: http://downloads.sourceforge.net/project/astyle/astyle/astyle%20{{ version }}/AStyle_{{ version }}_windows.zip # [win]
#   md5: 766a6b9fb9205737c046f4a81638b736 # [win]

  patches:
    - makefile_osx.patch # [osx]
    - makefile_linux.patch # [linux]

build:
  number: 0
  detect_binary_files_with_prefix: True
  skip: True  # [win]

about:
  home: http://astyle.sourceforge.net
  license: GPLv3
  license_file: doc/license.html
  summary: Artistic Style - A free, fast, and small automatic formatter for C, C++, C++/CLI, Objective‑C, C#, and Java source code
