{% set version = "0.1.x" %}  # 0.1.0 not compatible with most recent ismrmrd
{% set dyn_ext = ".so" %}  # [linux]
{% set dyn_ext = ".dylib" %}  # [osx]
{% set dyn_ext = ".dll" %}  # [win]
{% set exe = ".exe" %}  # [win]
{% set exe = "" %}  # [unix]

package:
  name: philips_to_ismrmrd
  version: {{ version }}

source:
    # fn: philips_to_ismrmrd-{{ version }}.tar.gz
    git_url: https://github.com/ismrmrd/philips_to_ismrmrd.git
    git_branch: master
    # git_url: https://github.com/grlee77/philips_to_ismrmrd.git
    # git_branch: link_fix
# https://github.com/ismrmrd/philips_to_ismrmrd/archive/v{{ version }}.tar.gz
# sha256: 160067d2d14923566f506d95c12ba6e207ceea0205c6e82da7e43594924e9ced


build:
  number: 0
#   skip: True  # [win]

requirements:
  build:
    - cmake
    - toolchain
#     - boost 1.63.*
#     - hdf5 1.8.17|1.8.17.*  # [unix]
    - ismrmrd 1.3.3    # compatible with philips_to_ismrmrd master, but not 0.1.0
    - libxml2 2.9.*
    - libxslt
  run:
#    - boost 1.63.*
#    - hdf5 1.8.17|1.8.17.*  # [unix]
    - ismrmrd 1.3.3
    - libxml2 2.9.*
    - libxslt

test:
  commands:
    - philips_to_ismrmrd --help > help.txt

about:
    home: https://github.com/ismrmrd/philips_to_ismrmrd
    license: ISMRMRD
    license_file: LICENSE
    summary: Philips raw data to ISMRMRD converter.

extra:
    recipe-maintainers:
      - grlee77
