package:
  name: libflame
  version: 5.1.0+36

source:
  git_url: git@github.com:flame/libflame.git
  git_tag: e6d7a296a76d8751203facb00a9acc3020e07518

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - gcc
    - libgfortran

  run:
    - libgfortran

test:
  commands:
    - test -f ${PREFIX}/lib/libflame.a
    - test -f ${PREFIX}/lib/libflame.so     # [linux]
    - test -f ${PREFIX}/lib/libflame.dylib  # [osx]

about:
  home: http://www.cs.utexas.edu/~flame/web/libFLAME.html
  license: LGPL v2.1
  license_file: LICENSE
  summary: High-performance object-based library for dense linear algebra computations
