{% set version = "5.1.0+34" %}

{% set variant = "openblas" %}

package:
  name: libflame
  version: {{ version }}

source:
  git_url: git@github.com:flame/libflame.git
  git_tag: 6e6ccb273c59eee7d61995a8edf821c125134af3

build:
  detect_binary_files_with_prefix: true
  skip: true  # [win]
  number: 200
  features:
    - blas_{{ variant }}

requirements:
  build:
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - gcc
  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - libgcc

test:
  commands:
    - test -f ${PREFIX}/lib/libflame.a
    - test -f ${PREFIX}/lib/libflame.so  # [linux]
    - test -f ${PREFIX}/lib/libflame.dylib  # [osx]

about:
  home: http://www.cs.utexas.edu/~flame/web/libFLAME.html
  license: LGPL v2.1
  summary: High-performance object-based library for DLA computations
