{% set version = "0.1.3.1" %}
# TODO: fix version string

package:
  name: kiwisolver
  version: {{ version }}

source:
  git_url: https://github.com/nucleic/kiwi/
  git_branch: master

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - gcc
  run:
    - python
    - libgcc

test:
  requires:
    - nose
  imports:
    - kiwisolver
  commands:
    - nosetests ${SRC_DIR}/py/tests

about:
  home: http://docs.enthought.com/apptools/
  license: BSD 3-clause? (COPYING states New BSD, but 4-clauses are listed)
  summary: Kiwi is an efficient C++ implementation of the Cassowary constraint solving algorithm

extra:
  recipe-maintainers:
    - grlee77
